### PR TITLE
Made gradient less vibrant and changed RGB codes to Hex codes

### PR DESCRIPTION
**Pull request by rocketbear27**
## Changes
I changed the RGB color codes to a different Hex color code format. After, I changed the gradients and base colors of the website to be less vibrant to the eyes, (See Issue #1 )

## Files
- `index.css`

## Comments
- This is just a preference, you may decline or tweak the colors as you would like 👍

### CODE REVIEW

**Comment by naclcaleb** [comment]
I don't see any changes to the gradient. Could you explain what those changes are?

**Comment by rocketbear27** [comment]
Just for clarification, all the styles are packed into `index.css` right?

**Comment by naclcaleb** [comment]
Yes, or most of them anyway...

**Comment by rocketbear27** [comment]
Do you have a build script in this repo?

**Comment by rocketbear27** [comment]
I fixed some code but if it didn't show up, hmm, I only made the colors a bit dimmer

**Comment by naclcaleb** [comment]
Well, ok then I'll go ahead and merge 👍

Also, I'm noticing that the MailChimp subscribe form has been distorted a bit. It should be a pretty simple bug to fix, if you want to work on that as well.

**Comment by naclcaleb** [comment]
However, we are planning on redesigning the site completely soon, so your work may be overwritten at some point.

**Comment by rocketbear27** [comment]
Ok, no problem, although, may I suggest feedback after the site is redesigned and I might work on some bugs. I would recommend your team to create some docs for contributors.

**Comment by naclcaleb** [comment]
Yea...the website isn't a big enough operation for us to take the time to write docs on it. 

We don't even have complete documentation for our backend API yet.

We need to focus our work on the things that are necessary for the app. The whole team is busy at the moment, and I may be taking a break from development for a while.

**Comment by rocketbear27** [comment]
Are your goals to make this a successful startup or?

**Comment by naclcaleb** [comment]
Yes, that is sort of the plan; although more importantly it's something to put on a resume 😉

**Comment by rocketbear27** [comment]
Yes, it is 😄

**Pull request merged**
